'use client'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Nav from '@/app/(components)/Nav'
import Contact from '@/app/Pages/Contact'
import About from '@/app/Pages/About'
import './globals.css'
import Projects from './Pages/Projects'


const inter = Inter({ subsets: ['latin'] })

// export const metadata: Metadata = {
//   title: 'My Portfolio',
//   description: 'Generated by create next app',
// }

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className='flex flex-col h-screen max-h-screen'>
          <Nav />
          <About />
          <Projects />
          <Contact />
        </div>
      </body>
    </html>
  )
}
